<?php

$host = 'localhost';
$user = 'root';
$pass = '';
$db = 'probook';
$mysqli = new mysqli($host, $user, $pass, $db) or die($mysqli->error);


$title = array(
    "Accel World",
    "Magi: The Kingdom of magic ",
    "Nagi no Asukara",
    "Unbreakable Machine Doll",
    "Accel World OVA",
    "GJ-bu OVA",
    "Sword Art Online - Extra edition",
    "Sword Art Online",
    "Servant x Service",
    "Boku ha Tomodachi ga Sukunai Next",
    "Ore no Kanojo to osananaji ga Shuraba Sugiru",
    "Chuunibyou demo Koi ga Shitai - Ren",
    "D-Frag",
    "Love Live 2",
    "Hanayamata",
    "Persona 4 Golden the Animation",
    "Gekkan Shoujo Nozaki-kun",
    "Sword Art Online II",
    "Selector Spread WIXOSS",
    "Trinity Seven",
    "Fate Stay Night : Unlimited Blade Works",
    "Shigatsu wa Kimi no Uso",
    "Saenai Heroine no Sodatekata",
    "The IdolM@ster : Cinderella Girls",
    "Ansatsu Kyoushitsu",
    "Plastic Memories",
    "Danmachi",
    "Aldnoah Zero 2",
    "Nisekoi S2",
    "Himouto Umaru-chan",
    "Yamada-kun to 7-nin no Majo",
    "Yamada-kun to 7-nin no Majo OVA",
    "Fate Stay Night : Unlimited Blade Works II",
    "Shoukugeki no Souma",
    "Working !!!",
    "Gate - Jietai Kanochi nite",
    "The IdolMaster Cinderella Girls II",
    "Gakusen Toshi Asterisk",
    "Gakkou Gurashi",
    "Fate kaleid Liner Prisma Ilya 2wei Herz",
    "Nisekoi OVA",
    "Nisekoi S2 OVA",
    "Trinity Seven OVA",
    "Charlotte OVA",
    "Himouto Umaru-chan OVA",
    "Shigatsu wa Kimi no Uso OVA",
    "Taimadou Gakuen 35 Shiken Shoutai",
    "Boku dake ga Inai Machi",
    "Hai to Gensou no Grimgar",
    "Hai to Gensou no Grimgar OVA",
    "Gate II - Jieitai Kanochi nite, Kaku Tatakaeri",
    "Kono Subarashii Sekai ni Shukufuku wo",
    "Saijaku Muhai no Bahamut",
    "Girl Und Panzer Movie - Ova",
    "Girl Und Panzer movie",
    "Ansatsu Kyoushitsu II",
    "Barakamon",
    "Gin no Saji",
    "Gin no Saji S2",
    "Mayoiga",
    "Kimi no Na wa",
    "Gakusen Toshi Asterisk II",
    "Re Zero kara Hajimaru Isekai Seikatsu",
    "Netoge no Yome wa Onnanoko ja Nai to Omotta",
    "Re Life ",
    "Shokugeki no Soma Ni no Sara",
    "Fate Kaleid Liner PRISMA ILYA 3rei",
    "Handa-kun",
    "Kono Bijutsubu ni wa Mondai ga Aru",
    "Zuto Mae kara Suki Deshita",
    "Orange",
    "New Game",
    "Shuumatsu no Izetta",
    "WWW.Working !!",
    "Kuzu no Honkai",
    "Kono Subarashii Sekai ni Shukufuku wo II",
    "Koe no Katachi",
    "Lostorage Incited WIXOSS ",
    "Seiren",
    "Saenai Heroine no Sodatekata ♭",
    "Shingeki no Kyojin II",
    "Masamune-kun no Revenge",
    "Danmachi Gaiden: Sword Oratoria",
    "Rokudenashi Majutsu Koushi to Akashic Records",
    "Sword Art Online : Ordinal Scale",
    "Kuroshitsuji : Book of Atlantis",
    "Tsuki ga Kirei",
    "Zero kara Hajimeru Mahou no Sho",
    "Sakurada Reset",
    "New Game !!",
    "Gamers",
    "Kakegurui",
    "Re:Creators",
    "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu",
    "Fate Apocrypha",
    "Just Because",
    "Boku no Kanojo ga Majimesugiru Shojo Bitch na Ken",
    "Ousama Game the Animation",
    "Shokugeki no Soma : San no Sara",
    "Koi to Uso",
    "Blend S",
    "Shuumatsu Nani Shitemasu ka? (Sukasuka)",
    "Mahou Tsukai no Yome",
    "Violet Evergarden",
    "Himouto! Umaru-chan R",
    "Karakai Jouzu no Takagi-san",
    "Kokkoku",
    "Isekai wa Smartphone to Tomo Movie - Take on Me",
    "Fate Kaleid Liner Prisma Ilya - Oath Under Snow",
    "No Game No Life Zero",
    "Love Live! The School Idol Movie",
    "Lostorage Conflated WIXOSS",
    "Shokugeki no Souma - San no Sara - Toutsuki Ressha-hen",
    "Wotaku ni Koi wa Muzukashii",
    "Sword Art Online Alternative - Gun Gale Online",
    "Citrus",
    "Chuunibyou demo Koi ga Shitai - Ren",
    "Darling in the FranXX",
    "Beatless",
    "Hinamatsuri");

$author = array(
    "Xi Jinping	China	65",
    "Vladimir Putin	Russia	66",
    "Donald Trump	United States	72",
    "Angela Merkel	Germany	64",
    "Jeff Bezos	Amazon.com	54",
    "Pope Francis	Roman Catholic Church	81",
    "Bill Gates	Bill & Melinda Gates Foundation	62",
    "Mohammed bin Salman Al Saud	Saudi Arabia	33",
    "Narendra Modi	India	68",
    "Larry Page	Alphabet	45",
    "Jerome H. Powell	United States	65",
    "Emmanuel Macron	France	40",
    "Mark Zuckerberg	Facebook	34",
    "Theresa May	United Kingdom	62",
    "Li Keqiang	China	63",
    "Warren Buffett	Berkshire Hathaway	88",
    "Ali Hoseini-Khamenei	Iran	79",
    "Mario Draghi	European Central Bank	71",
    "Jamie Dimon	Chase	62",
    "Carlos Slim Helu	América Móvil	78",
    "Jack Ma	Alibaba Group	54",
    "Christine Lagarde	International Monetary Fund	62",
    "Doug McMillon	Wal-Mart Stores	52",
    "Tim Cook	Apple	57",
    "Elon Musk	Tesla	47",
    "Benjamin Netanyahu	Israel	69",
    "Ma Huateng	Tencent Holdings	46",
    "Larry Fink	BlackRock	65",
    "Akio Toyoda	Toyota Motor	62",
    "John L. Flannery	General Electric	57",
    "Antonio Guterres	United Nations	69",
    "Mukesh Ambani	Reliance Industries Ltd.	61",
    "Jean-Claude Juncker	European Union	63",
    "Darren Woods	ExxonMobil	53",
    "Sergey Brin	Alphabet	45",
    "Kim Jong-un	North Korea	34",
    "Charles Koch	Koch Industries	82",
    "Shinzo Abe	Japan	64",
    "Rupert Murdoch	News Corp	87",
    "Satya Nadella	Microsoft	51",
    "Jim Yong Kim	World Bank	58",
    "Stephen Schwarzman	Blackstone Group	71",
    "Khalifa bin Zayed Al-Nahyan	United Arab Emirates	70",
    "Haruhiko Kuroda	Japan	73",
    "Abdel Fattah el-Sisi	Egypt	63",
    "Li Ka-shing	CK Hutchison Holdings	90",
    "Lloyd Blankfein	Goldman Sachs Group	64",
    "Recep Tayyip Erdogan	Turkey	64",
    "Bob Iger	Walt Disney	67",
    "Michel Temer	Brazil	78",
    "Michael Bloomberg	Bloomberg	76",
    "Wang Jianlin	Dalian Wanda Group	64",
    "Mary Barra	General Motors	56",
    "Moon Jae-in	South Korea	65",
    "Masayoshi Son	Softbank	61",
    "Bernard Arnault	LVMH Moet Hennessy Louis Vuitton	69",
    "Justin Trudeau	Canada	46",
    "Robin Li	Baidu	49",
    "Michael Dell	Dell	53",
    "Hui Ka Yan	China Evergrande Group	60",
    "Lee Hsien Loong	Singapore	66",
    "Bashar al-Assad	Syria	53",
    "John Roberts	United States	63",
    "Enrique Pena Nieto	Mexico	52",
    "Ken Griffin	Citadel LLC	50",
    "Aliko Dangote	Dangote Group	61",
    "Mike Pence	United States	59",
    "Qamar Javed Bajwa	Pakistan	57",
    "Rodrigo Duterte	Philippines	73",
    "Abigail Johnson	Fidelity Investments	56",
    "Reed Hastings	-	58",
    "Robert Mueller	United States	74",
    "Abu Bakr al-Baghdadi	Islamic State	47",
    "Joko Widodo	Indonesia	57",
    "Gianni Infantino	FIFA	48"
);

function addBook($mysqli, $bookDetail)
{
    $id = $bookDetail['id'];
    $title = $bookDetail['title'];
    $amount = $bookDetail['amount'];
    $author = $bookDetail['author'];
    $desc = $bookDetail['description'];
    $img = $bookDetail['img'];

    $queryString = "INSERT INTO books values ($id, '$title', $amount, '$author', '$desc', '$img')";
    $mysqli->query($queryString);
};

for ($i = 1; $i <= 100; $i++) {
    $bookDetail = array(
        "id" => $i + 1000,
        "title" => $title[$i],
        "amount" => rand(1, 10),
        "author" => $author[array_rand($author, 1)],
        "description" => "lorem itsum dorol dnsnadk",
        "img" => "../View/Src/book/thumbnail_" . str_pad($i, 3, '0', STR_PAD_LEFT). ".jpg"
    );
    addBook($mysqli, $bookDetail);
};
